# Generated by Django 4.2.2 on 2023-06-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='visited_times',
            field=models.BigIntegerField(default=0),
        ),
    ]
